function [t_ms, T_sps1, T_sps2, heating, U_in] = import_step_response(filename, numVars, dataLines)
%IMPORTFILE Import data from a text file
%  [T_MS, T_SPS1, T_SPS2, HEATING, U_IN] = IMPORTFILE(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  data as column vectors.
%
%  [T_MS, T_SPS1, T_SPS2, HEATING, U_IN] = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [t_ms, T_sps1, T_sps2, heating, U_in] = importfile("H:\01_Lehre\20_IKA\Labortag\Temperatur_Regelung_Teaching_Factory\data\Volt1OhneVentilation.csv", [14, 13428]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-May-2024 17:27:07

%% Input handling

if nargin < 2
    numVars = 5;
end

% If dataLines is not specified, define defaults
if nargin < 3
    dataLines = [14, inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", numVars);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["t_ms", "T_sps1", "T_sps2", "heating", "U_in"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["t_ms", "T_sps1", "T_sps2", "heating", "U_in"], "ThousandsSeparator", ",");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
t_ms = tbl.t_ms;
T_sps1 = tbl.T_sps1;
T_sps2 = tbl.T_sps2;
heating = tbl.heating;
U_in = tbl.U_in;

t_ms = t_ms(1:end-1);
T_sps1 = T_sps1(1:end-1);
T_sps2 = T_sps2(1:end-1);
heating = heating(1:end-1);
U_in = U_in(1:end-1);

end